language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  chmod +x gradlew
script: "./gradlew clean build"

# Bucket
before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIA35W32QHSG3QW2WXS
    secret_access_key: 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
    bucket: mybucket-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: AKIA35W32QHSG3QW2WXS
    secret_access_key: 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
    bucket: mybucket-springboot-build
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: codedeploy-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true



# CI complete
notifications:
  email:
    recipients:
      - guen9310@gmail.com